targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          # To use ISO 8601 strings
          # store_date_time_values_as_text: true
