name: authentication_repository
description: Dart package which manages the authentication domain.
version: 2.0.0
publish_to: none

environment:
  sdk: ">=3.0.0-417.1.beta <=3.1.1"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  meta: ^1.8.0

dev_dependencies:
  firebase_auth_platform_interface: ^6.16.0
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.1.5
  very_good_analysis: ^5.0.0
